version: '2'
services:
    tpwebsite-app:
        image: tpwebsite
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tpwebsite-mysql:3306/tpwebsite?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://tpwebsite-elasticsearch:9200
        ports:
            - 8080:8080
    tpwebsite-mysql:
        extends:
            file: mysql.yml
            service: tpwebsite-mysql
    tpwebsite-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tpwebsite-elasticsearch
